arguments=[
    {
        name="player"
        type="Player"
    },{
        name="item"
        type="Item"
    },{
        name="quantity"
        type="Integer"
        meta {
            range="[1,64]"
        }
    }
]
executors=[
    {
        command="clear <player> <item> quantity>"
        source="server"
        wait=500
    },
    {
        command="give <player> <item> quantity>"
        source="server"
    }
]
